### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by aravinat21** [Xithrius/twitch-tui#182]
**Describe the bug:**
High CPU usage

**To Reproduce:**
`twt`

**Expected behavior:**
low CPU

**Screenshots:**
TBD

**System:**
- Twitch-tui version:1.6.0

- Operating System:5.18.12-artix-1

- Terminal:st

- Shell:zsh

Issue is not consistent

**Comment by Xithrius** [comment]
Hello,

Could you define "high cpu usage", in your case?

This might be solved in one of the alphas that is currently under development for v2.0.

**Comment by aravinat21** [comment]
Close to 100% out of 400% which I thought should be unusual.

**Comment by Xithrius** [comment]
Does this happen usually at launch or when the application is running for a while?

Are you able to connect and see messages before or after the CPU spikes?

**Comment by aravinat21** [comment]
I could not reproduce it again either. Maybe it's just a onetime thing.

Noticed it after about an hour of usage. Then restarted and it was still using 100% of CPU.

not applicable (it was a channel with zero viewers)

No. It did not solve it. I raised it to 1000 (ms). Maybe it did solve the issue. I will put it to test again.

```toml
[twitch]
# Your username on Twitch.
username = "aravinat21"
# The streamer's name.
channel = "aravinat21" # A channel with 0 viewers
# The IRC channel you'd like to connect to.
server = "irc.chat.twitch.tv"
# OAuth token that authenticates you into Twitch. Acquired through https://twitchapps.com/tmi/.
token = ""

[terminal]
# The delay in milliseconds between terminal updates.
tick_delay = 1000
# The maximum amount of messages to be stored.
maximum_messages = 150
# The file path to log to.
log_file = ""

[storage]
# If previous channels switched to should be tracked.
channels = true
# If previous username mentions should be tracked.
mentions = true

[filters]
# If filters should be enabled at all.
enabled = false
# If the regex filters should be reversed.
reversed = false

[frontend]
# If the time and date is to be shown.
date_shown = true
# The format of the date and time outputs. Formats can be found at https://strftime.org/.
date_format = "%a %b %e %T %Y"
# The longest a username can be.
maximum_username_length = 26
# Which side the username should be aligned to.
username_alignment = "right"
# The color palette for the username column: pastel (default), vibrant, warm, cool.
palette = "pastel"
# Show title with time and channel.
title_shown = true
# Show padding around chat frame.
padding = true
# Show twitch badges next to usernames.
badges = true
```
