### ISSUE TITLE
Emotes don't seem to be downloaded after editing config and running twt

### ISSUE THREAD

**Issue by LukyLurks** [Xithrius/twitch-tui#611]
**Describe the bug:**

Emotes don't appear in the terminal or in `~/.cache/twt/` after following the [configuration instructions](https://xithrius.github.io/twitch-tui/guide/configuration.html).

**To Reproduce:**

1. `sudo pacman -Syu twitch-tui`
2. run `twt` in `kitty`, complete the config wizard, then exit with `q`
3. set `twitch_emotes` and `betterttv_emotes` to `true` in `~/.config/twt/config.toml`
4. `twt` then connect to any chat
5. `Alt`+`e` to bring up the emote menu: it is empty
6. send "PogChamp" in the chat: the text "PogChamp" appears and not the emote

**Expected behavior:**

I expected either the menu to contain emotes, or that the emote PogChamp would appear in the terminal when sending "PogChamp". I also expected `~/.cache/twt/` to have been populated at some point in the process, as indicated in the [documentation](https://xithrius.github.io/twitch-tui/guide/configuration.html#emotes).

**Screenshots:**

**System:**

- Twitch-tui version: 2.6.10-1

- Operating System: Arch Linux w/ kernel 6.9.3-arch1-1

- Terminal: kitty 0.35.1

- Shell: Bash 5.2.26(1)-release

**Additional context:**
I also tried uninstalling `twitch-tui` with `pacman`, removed the config and cache directories, reinstalled with `cargo` (`twitch-tui` version 2.6.10), and ran the exact same steps, with the same results.

**Comment by Xithrius** [comment]
Thanks for the issue. I'll try to diagnose what's going on within the next few hours.

**Comment by Xithrius** [comment]
I haven't been able to reproduce the issue as of now, although I am running the same system as you. I'll do a deeper dive in the near future.

**Comment by LukyLurks** [comment]
Thanks for the quick replies! Feel free to ask for any details/screenshots/screen recordings, or if you need me to try things, when you get to it. I couldn't find similar reported issues, so I'm not excluding the possibility that I just did something silly on my end; I'll report back if it ends up being the case.

**Comment by Xithrius** [comment]
Could you send your entire config? Without the token, of course.

**Comment by LukyLurks** [comment]
> Could you send your entire config? Without the token, of course.
```toml
[twitch]
username = "luky75"
channel = "luky75"
server = "irc.chat.twitch.tv"
token = "redacted"

[terminal]
delay = 30
maximum_messages = 500
verbose = false
first_state = "Dashboard"

[storage]
channels = false
mentions = false

[filters]
enabled = false
reversed = false

[frontend]
show_datetimes = true
datetime_format = "%T"
username_shown = true
palette = "pastel"
title_shown = true
margin = 0
badges = false
theme = "dark"
username_highlight = true
state_tabs = false
cursor_shape = "user"
blinking_cursor = false
inverted_scrolling = false
show_scroll_offset = false
twitch_emotes = true
betterttv_emotes = true
seventv_emotes = false
frankerfacez_emotes = false
favorite_channels = []
recent_channel_count = 5
border_type = "plain"
hide_chat_border = false
right_align_usernames = false
show_unsupported_screen_size = true
```
