### ISSUE TITLE
"Terminal cell_size must be defined when emotes are enabled"

### ISSUE THREAD

**Issue by slimelia** [Xithrius/twitch-tui#612]
**Describe the bug:**
When trying to launch a Twitch channel chat in twitch-tui version 2.6.11, I get the error _"Terminal cell_size must be defined when emotes are enabled"_. This error did not occur in prior versions. Emotes are *not* enabled in the config file.

**To Reproduce:**
1. Run `twt` in command-line
2. Press _Enter_ key to enter currently selected channel
3. Chat window briefly appears
4. Twitch-tui crashes

**Expected behavior:**
Twitch-tui should recognise emotes are not enabled and display the chat.

**Screenshots:**
![image](https://github.com/Xithrius/twitch-tui/assets/19677816/c718af20-f997-4b14-84b8-a31120a83e04)

**System:**
- Twitch-tui version: 2.6.11
- Operating System: WSL 2 (Ubuntu 22.04.4 LTS on Windows 10 x86_64)
- Terminal: Windows Terminal
- Shell: GNU bash, version 5.1.16(1)-release

**Additional context:**
This bug was not present prior to version 2.6.11; when I try running version 2.6.10 I can open the chat without issue.

EDIT - thought it might be pertinent to include a copy of my config file:
```toml
[twitch]
username = "slimelia"
channel = "kipbite"
server = "irc.chat.twitch.tv"
token = "REDACTED"

[terminal]
delay = 30
maximum_messages = 500
verbose = false
first_state = "Dashboard"

[storage]
channels = false
mentions = false

[filters]
enabled = false
reversed = false

[frontend]
show_datetimes = true
datetime_format = "%a %b %e %T %Y"
username_shown = true
palette = "pastel"
title_shown = true
margin = 0
badges = false
theme = "dark"
username_highlight = true
state_tabs = false
cursor_shape = "user"
blinking_cursor = false
inverted_scrolling = false
show_scroll_offset = false
twitch_emotes = false
betterttv_emotes = false
seventv_emotes = false
frankerfacez_emotes = false
favorite_channels = []
recent_channel_count = 5
border_type = "plain"
hide_chat_border = false
right_align_usernames = false
show_unsupported_screen_size = true
```
