### ISSUE TITLE
Subscriber emotes from some channels don't show when I'm the one using them

### ISSUE THREAD

**Issue by LukyLurks** [Xithrius/twitch-tui#615]
**Describe the bug:**
- Emotes from 2 of the 3 channels I am subscribed to remain in text form when I send them, and can't be found in the `Alt`+`e` menu.
- Emotes from these 2 channels show correctly when sent by other people.
- Emotes from these 2 channels show correctly in twitch-tui, when I send them through the twitch.tv chat (see screenshot)

**To Reproduce:**
I don't have reliable steps since it's my specific situation. The best I can suggest is:
1. Be subscribed to at least 2 channels.
2. Attempt to send messages containing the related subscriber emotes: emotes from one channel may remain in text form when sent.
3. Attempt to find the subscriber emotes in the popup menu: emotes from one channel may not be found.

**Expected behavior:**
- I expect emotes to display as images when sent, and to show up in the popup menu when searched.

**Screenshots:**
![sshot_2024_06_18_23_25_43](https://github.com/Xithrius/twitch-tui/assets/20930768/fc7daf0c-36ae-474d-9e94-7bb3b81b1a53)

**System:**

- Twitch-tui version: 2.6.11

- Operating System: Linux 6.9.5-arch1-1

- Terminal: kitty 0.35.1

- Shell: bash 5.2.26(1)-release

- config.toml:
```toml
[twitch]
username = "Luky75"
channel = "luky75"
server = "irc.chat.twitch.tv"
token = "redacted"

[terminal]
delay = 30
maximum_messages = 500
verbose = false
first_state = "Dashboard"

[storage]
channels = false
mentions = false

[filters]
enabled = false
reversed = false

[frontend]
show_datetimes = true
datetime_format = "%T"
username_shown = true
palette = "pastel"
title_shown = true
margin = 0
badges = true
theme = "dark"
username_highlight = true
state_tabs = false
cursor_shape = "user"
blinking_cursor = true
inverted_scrolling = false
show_scroll_offset = false
twitch_emotes = true
betterttv_emotes = true
seventv_emotes = false
frankerfacez_emotes = true
favorite_channels = []
recent_channel_count = 5
border_type = "plain"
hide_chat_border = true
right_align_usernames = false
show_unsupported_screen_size = true
```

**Additional context:**
- If this issue is hard to diagnose on your own because you're not subscribed to multiple channels, feel free to ask me to do "technical" stuff. I don't know much about Rust, therefore I'd be happy to have an excuse to get into it.
